# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\tooltest_py\serialProject\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1137, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Data_Display = QtWidgets.QTextEdit(self.centralwidget)
        self.Data_Display.setGeometry(QtCore.QRect(10, 20, 819, 419))
        self.Data_Display.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Data_Display.setObjectName("Data_Display")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 470, 69, 19))
        self.label_2.setObjectName("label_2")
        self.Send_Data = QtWidgets.QPushButton(self.centralwidget)
        self.Send_Data.setGeometry(QtCore.QRect(10, 610, 93, 28))
        self.Send_Data.setObjectName("Send_Data")
        self.Send_Data_Display = QtWidgets.QTextEdit(self.centralwidget)
        self.Send_Data_Display.setGeometry(QtCore.QRect(10, 490, 819, 109))
        self.Send_Data_Display.setObjectName("Send_Data_Display")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 69, 19))
        self.label.setObjectName("label")
        self.Com_Band = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Band.setGeometry(QtCore.QRect(890, 70, 129, 21))
        self.Com_Band.setObjectName("Com_Band")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(840, 70, 49, 19))
        self.label_4.setObjectName("label_4")
        self.Com_Port = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Port.setGeometry(QtCore.QRect(890, 30, 129, 21))
        self.Com_Port.setObjectName("Com_Port")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 30, 49, 19))
        self.label_3.setObjectName("label_3")
        self.Open_Com = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Com.setGeometry(QtCore.QRect(840, 100, 93, 28))
        self.Open_Com.setObjectName("Open_Com")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 450, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(840, 400, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(840, 500, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1137, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Send_Data.clicked.connect(MainWindow.send_data_click) # type: ignore
        self.Open_Com.clicked.connect(MainWindow.open_com_click) # type: ignore
        self.pushButton.clicked.connect(self.Data_Display.clear) # type: ignore
        self.pushButton.clicked.connect(self.Send_Data_Display.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "serial_tool"))
        self.label_2.setText(_translate("MainWindow", "发送窗口"))
        self.Send_Data.setText(_translate("MainWindow", "发送数据"))
        self.label.setText(_translate("MainWindow", "数据窗口"))
        self.label_4.setText(_translate("MainWindow", "波特率"))
        self.label_3.setText(_translate("MainWindow", "串口号"))
        self.Open_Com.setText(_translate("MainWindow", "打开串口"))
        self.pushButton.setText(_translate("MainWindow", "清空窗口"))
        self.checkBox.setText(_translate("MainWindow", "Hex显示"))
        self.checkBox_2.setText(_translate("MainWindow", "Hex发送"))
